### ISSUE TITLE
Cannot install the package

### ISSUE THREAD

**Issue by on3dd** [adexin/spinners-react#3]
Hi! I liked your spinners kit, and it seems that I have already used it. However, when I try to install it now, I get the following error:
```
$ npm install spinners-react

npm ERR! code E404
npm ERR! 404 Not Found - GET https://packagecloud.io/golang-migrate/migrate/npm/spinners-react/-/spinners-react-1.0.4.tgz
npm ERR! 404 
npm ERR! 404  'spinners-react@https://packagecloud.io/golang-migrate/migrate/npm/spinners-react/-/spinners-react-1.0.4.tgz' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/on3dd/.npm/_logs/2021-01-10T12_18_32_833Z-debug.log
```

And complete log from error above:
```
# /home/on3dd/.npm/_logs/2021-01-10T12_18_32_833Z-debug.log

0 verbose cli [
0 verbose cli   '/home/on3dd/.nvm/versions/node/v15.5.0/bin/node',
0 verbose cli   '/home/on3dd/.nvm/versions/node/v15.5.0/bin/npm',
0 verbose cli   'install',
0 verbose cli   'spinners-react'
0 verbose cli ]
1 info using npm@7.3.0
2 info using node@v15.5.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/home/on3dd/.nvm/versions/node/v15.5.0/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/home/on3dd/code/mern-ssr-blog/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/home/on3dd/.npmrc Completed in 2ms
11 timing config:load:user Completed in 2ms
12 timing config:load:file:/home/on3dd/.nvm/versions/node/v15.5.0/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 verbose npm-session c34657bbf2a3163a
20 timing npm:load Completed in 17ms
21 timing arborist:ctor Completed in 1ms
22 timing idealTree:init Completed in 1062ms
23 timing idealTree:userRequests Completed in 6ms
24 silly idealTree buildDeps
25 silly fetch manifest spinners-react@*
26 http fetch GET 200 https://registry.npmjs.org/spinners-react 2320ms (from cache)
27 silly fetch manifest @types/react@^16.9.49
28 http fetch GET 304 https://registry.npmjs.org/@types%2freact 931ms (from cache)
29 silly fetch manifest @types/react-dom@^16.9.8
30 http fetch GET 304 https://registry.npmjs.org/@types%2freact-dom 453ms (from cache)
31 silly fetch manifest react@^16.13.1
32 http fetch GET 304 https://registry.npmjs.org/react 439ms (from cache)
33 silly fetch manifest react-dom@^16.13.1
34 http fetch GET 304 https://registry.npmjs.org/react-dom 436ms (from cache)
35 silly placeDep ROOT spinners-react@1.0.4 OK for: mern-ssr-blog@0.1.0 want: *
36 timing idealTree:#root Completed in 4609ms
37 timing idealTree:node_modules/spinners-react Completed in 0ms
38 timing idealTree:buildDeps Completed in 4609ms
39 timing idealTree:fixDepFlags Completed in 16ms
40 timing idealTree Completed in 5697ms
41 timing reify:loadTrees Completed in 5697ms
42 timing reify:diffTrees Completed in 31ms
43 silly reify mark retired [ '/home/on3dd/code/mern-ssr-blog/node_modules/spinners-react' ]
44 silly reify moves {
44 silly reify   '/home/on3dd/code/mern-ssr-blog/node_modules/spinners-react': '/home/on3dd/code/mern-ssr-blog/node_modules/.spinners-react-YPj0nQXr'
44 silly reify }
45 timing reify:retireShallow Completed in 2ms
46 timing reify:createSparse Completed in 2ms
47 timing reify:loadBundles Completed in 0ms
48 silly tarball no local data for spinners-react@https://packagecloud.io/golang-migrate/migrate/npm/spinners-react/-/spinners-react-1.0.4.tgz. Extracting by manifest.
49 http fetch POST 404 https://packagecloud.io/golang-migrate/migrate/npm/-/npm/v1/security/advisories/bulk 307ms
50 http fetch POST 404 https://packagecloud.io/golang-migrate/migrate/npm/-/npm/v1/security/audits/quick 315ms
51 verbose audit error Error: 404 Not Found - POST https://packagecloud.io/golang-migrate/migrate/npm/-/npm/v1/security/audits/quick
51 verbose audit error     at /home/on3dd/.nvm/versions/node/v15.5.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:123:15
51 verbose audit error     at async Map.[getReport] (/home/on3dd/.nvm/versions/node/v15.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:310:21)
51 verbose audit error     at async Map.run (/home/on3dd/.nvm/versions/node/v15.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:103:19)
51 verbose audit error  HttpErrorGeneral: 404 Not Found - POST https://packagecloud.io/golang-migrate/migrate/npm/-/npm/v1/security/audits/quick
51 verbose audit error     at /home/on3dd/.nvm/versions/node/v15.5.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:123:15
51 verbose audit error     at async Map.[getReport] (/home/on3dd/.nvm/versions/node/v15.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:310:21)
51 verbose audit error     at async Map.run (/home/on3dd/.nvm/versions/node/v15.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:103:19) {
51 verbose audit error   headers: [Object: null prototype] {
51 verbose audit error     date: [ 'Sun, 10 Jan 2021 12:18:34 GMT' ],
51 verbose audit error     'content-type': [ 'text/html' ],
51 verbose audit error     'content-length': [ '146' ],
51 verbose audit error     connection: [ 'keep-alive' ],
51 verbose audit error     server: [ 'nginx' ],
51 verbose audit error     'x-fetch-attempts': [ '1' ]
51 verbose audit error   },
51 verbose audit error   statusCode: 404,
51 verbose audit error   code: 'E404',
51 verbose audit error   method: 'POST',
51 verbose audit error   uri: 'https://packagecloud.io/golang-migrate/migrate/npm/-/npm/v1/security/audits/quick',
51 verbose audit error   body: <Buffer 3c 68 74 6d 6c 3e 0d 0a 3c 68 65 61 64 3e 3c 74 69 74 6c 65 3e 34 30 34 20 4e 6f 74 20 46 6f 75 6e 64 3c 2f 74 69 74 6c 65 3e 3c 2f 68 65 61 64 3e 0d ... 96 more bytes>,
51 verbose audit error   pkgid: 'quick'
51 verbose audit error }
52 silly audit error <html>
52 silly audit error <head><title>404 Not Found</title></head>
52 silly audit error <body>
52 silly audit error <center><h1>404 Not Found</h1></center>
52 silly audit error <hr><center>nginx</center>
52 silly audit error </body>
52 silly audit error </html>
53 timing auditReport:getReport Completed in 880ms
54 timing reify:audit Completed in 880ms
55 http fetch GET 404 https://packagecloud.io/golang-migrate/migrate/npm/spinners-react/-/spinners-react-1.0.4.tgz 1134ms
56 timing reify:rollback:createSparse Completed in 2ms
57 timing reify:rollback:retireShallow Completed in 1ms
58 timing command:install Completed in 6906ms
59 verbose stack Error: 404 Not Found - GET https://packagecloud.io/golang-migrate/migrate/npm/spinners-react/-/spinners-react-1.0.4.tgz
59 verbose stack     at /home/on3dd/.nvm/versions/node/v15.5.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:123:15
59 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:93:5)
60 verbose statusCode 404
61 verbose pkgid spinners-react@https://packagecloud.io/golang-migrate/migrate/npm/spinners-react/-/spinners-react-1.0.4.tgz
62 verbose cwd /home/on3dd/code/mern-ssr-blog
63 verbose Linux 4.19.128-microsoft-standard
64 verbose argv "/home/on3dd/.nvm/versions/node/v15.5.0/bin/node" "/home/on3dd/.nvm/versions/node/v15.5.0/bin/npm" "install" "spinners-react"
65 verbose node v15.5.0
66 verbose npm  v7.3.0
67 error code E404
68 error 404 Not Found - GET https://packagecloud.io/golang-migrate/migrate/npm/spinners-react/-/spinners-react-1.0.4.tgz
69 error 404
70 error 404 'spinners-react@https://packagecloud.io/golang-migrate/migrate/npm/spinners-react/-/spinners-react-1.0.4.tgz' is not in the npm registry.
71 error 404 You should bug the author to publish it (or use the name yourself!)
72 error 404 Note that you can also install from a
73 error 404 tarball, folder, http url, or git url.
74 verbose exit 1
```

Could you please help me with this problem? Thank you in advance! ❤️

**Comment by on3dd** [comment]
Oops, sorry for the fake issue, for some reason my `npm config` got corrupted 😕. Unfortunately, I only noticed this after another package failed to install for the same reason. 

For more information and solutions, see: https://stackoverflow.com/questions/47520181/installing-npm-package-fails-with-404
